#!/bin/sh

set -e

base="$(dirname "$(readlink -f $0)")"
cd "$base/iron-maud"

cargo clean
cargo doc

cd target/doc

git init
trap 'rm -rf .git/' 0

git add .
git commit -m 'Update documentation'

git remote add origin git@github.com:lfairy/maud.git
git push --force origin master:gh-pages
