[package]
name = "benchmarks"
version = "0.1.1"
authors = ["Chris Wong <lambda.fairy@gmail.com>"]

[dependencies]
maud = { path = "../maud" }
handlebars = "*"
horrorshow = "*"
liquid = "*"
rustc-serialize = "*"
serde = "*"
serde_derive = "*"
serde_json = "*"
tera = "*"
